### ISSUE TITLE
Doesn't generate correct DB output for members who changed party

### ISSUE THREAD

**Issue by mashedkeyboard** [everypolitician-scrapers/welsh-assembly-p39s#1]
See for example https://www.wikidata.org/wiki/Q24041564 - Neil McEvoy.

He initially sat in the Welsh Assembly as Plaid Cymru, but was suspended and therefore now sits as an independent. The generated Popolo data doesn't account for this, instead stating that his membership had an end date.

**Comment by mashedkeyboard** [comment]
Having looked into this further, it seems this was because Neil McEvoy's second term on Wikidata was missing the `term` attribute. With this having been added, the SPARQL query this uses seems to return both, so I assume it will update in due course.

Without term being set, there's no way for this data to have been meaningful in the first instance in the context of EveryPolitician, where the Popolo data is inherently related to terms, and as a consequence I'm closing this issue.

**Comment by tmtmtmtm** [comment]
Thanks for looking into this @mashedkeyboard. I've made a scraper a little bit more robust anyway, and triggered a fresh run, so that should make its way through very shortly.
